name: Node

on:
  pull_request:
    paths:
      - "ui/**"

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Build and Test
    defaults:
      run:
        working-directory: ui
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 12.x
        uses: actions/setup-node@v3
        with:
          node-version: 12.x
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Calculate bundle size
        id: bundle
        uses: ./.github/actions/bundle
      - name: Test
        run: npm run test
      - name: Coverage report
        id: coverage
        if: ${{ always() }}
        uses: ./.github/actions/coverage-report
      - name: Comment on PR
        if: ${{ always() }}
        uses: ./.github/actions/commenter
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUNDLE_SIZE: ${{ steps.bundle.outputs.bundle_size }}
          TEST_COVERAGE: ${{ steps.coverage.outputs.test_coverage }}

  lint:
    runs-on: ubuntu-22.04
    name: ESLint
    defaults:
      run:
        working-directory: ui

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 12.x
        uses: actions/setup-node@v3
        with:
          node-version: 12.x
      - name: Install Dependencies
        run: npm ci
      - name: Code lint
        run: npm run lint

  e2e-tests:
    runs-on: ubuntu-22.04 # or macos-latest, windows-latest
    defaults:
      run:
        working-directory: ui
    steps:
      - uses: actions/checkout@v4
      - name: Increase file watcher limit
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      - uses: actions/setup-node@v3
        with:
          node-version: 12.x
      - uses: microsoft/playwright-github-action@v1.5.6
      - name: Install dependencies
        run: npm ci
      - name: run tests
        run: npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: failures
          path: ui/e2e/failure_output
